# Generated by Django 3.2.25 on 2024-04-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_serial_number', models.IntegerField(blank=True, null=True)),
                ('device_config', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
