# Generated by Django 3.2.25 on 2024-04-30 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns_sensorsdata', '0002_trajectory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='標題')),
                ('video_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='視頻文件路徑')),
                ('depth_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='深度文件路徑')),
                ('pointcloud_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='點雲文件路徑')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
                ('calibration', models.TextField(blank=True, null=True, verbose_name='校準數據')),
                ('imu', models.TextField(blank=True, null=True, verbose_name='IMU數據')),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上傳時間')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sns_sensorsdata.sources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
                ('raw_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件路徑')),
                ('temperature_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='溫度文件路徑')),
                ('calibration', models.TextField(blank=True, null=True, verbose_name='校準數據')),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上傳時間')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='sns_sensorsdata.sources')),
            ],
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='位置')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路徑')),
                ('audio_text', models.TextField(blank=True, null=True, verbose_name='音頻文本')),
                ('upload_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='上傳時間')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='sns_sensorsdata.sources')),
            ],
        ),
    ]
